### ISSUE TITLE
FEAT: add chafa support

### ISSUE THREAD

**Issue by r3tr0ananas** [r3tr0ananas/wallhaven-cli#2]

**Comment by r3tr0ananas** [comment]
Hey @nxjosephofficial, I just wanted to mention that `chafa` support is now avaliable.

<img src="https://github.com/user-attachments/assets/4ea23308-004d-4390-923f-5411c7755b4a" height="100">

**Comment by nxjosephofficial** [comment]
Nice! thanks. I made a port for `wallhaven-cli v1.0.6` and submitted it to FreeBSD, btw.

**Comment by r3tr0ananas** [comment]
> Nice! thanks. I made a port for `wallhaven-cli v1.0.6` and submitted it to FreeBSD, btw. It's also available in [my personal FreeBSD ports repository](https://github.com/nxjosephofficial/yusuf-ports/tree/main/graphics/wallhaven-cli).

Nice :D
