### ISSUE TITLE
Config directory is not being created on run.

### ISSUE THREAD

**Issue by nxjosephofficial** [r3tr0ananas/wallhaven-cli#6]
Hi. I'm using version 2 and `wallhaven` doesn't run and it's complaining config directory doesn't exist. I think it should create it by itself.

![2024-10-10_14-47](https://github.com/user-attachments/assets/7a0a4087-84ec-4c94-877a-1ec82b22aa67)

I don't think this was an issue in version `1.0.6`.

Thanks.

**Comment by r3tr0ananas** [comment]
Fixed.

![image](https://github.com/user-attachments/assets/9ae0a1b5-a03b-4a9e-8534-d3712d2d3fbd)
