### ISSUE TITLE
Update Go module version

### ISSUE THREAD

**Issue by nxjosephofficial** [r3tr0ananas/wallhaven-cli#7]
Hi. Why Go module doesn't have recent versions? I do want to use the Go module to build the program on FreeBSD. Building with Github way gives some errors. Can you please update go module versions? Thanks.

![image](https://github.com/user-attachments/assets/31700145-1145-46d0-9fd4-8aff969962dd)

**Comment by nxjosephofficial** [comment]
I suspect that adding `/v2` makes it use the `v2` branch. I wonder if you need to update the `v2` branch because it seems to be outdated by 10 commits from main. Thanks.

**Comment by r3tr0ananas** [comment]
It shouldn't or atleast i don't think it doesn't

**Comment by nxjosephofficial** [comment]
Okay, if you say so. I think now I should wait for [pkg.go.dev](https://pkg.go.dev/github.com/r3tr0ananas/wallhaven-cli/wallhaven) to see the v2 versions, right?

**Comment by r3tr0ananas** [comment]
I published a version, so hopefully it updates.

**Comment by nxjosephofficial** [comment]
Okay, now pkg.go.dev has been updated and there is `v2` module now. Very thanks.
